import test from 'node:test';
import assert from 'node:assert/strict';
import {createState,appendLeader,replicateRecord,confirmReplication,learnHighWatermark,acknowledgeRecord,failBroker,electLeader,refreshMetadata,rediscoverCoordinator,availableRecords,receiveRecord,completeProcessing,storeCommit,acknowledgeCommit} from './broker-model.js';
const record=(sequence=0,extra={})=>({eventId:'dispute-49328:created',producerId:42,epoch:0,sequence,partition:0,...extra});
function replicated(state=createState(),entry=record()){const appended=appendLeader(state,entry);let current=appended.state;for(const id of current.isr.filter(id=>id!==current.leader))current=replicateRecord(current,id,appended.record.offset);return {state:confirmReplication(current),record:appended.record};}
function pure(fn,state,...args){const before=structuredClone(state);const result=fn(state,...args);assert.deepEqual(state,before,'Input was mutated');return result;}

test('append advances LEO while HW, consumer visibility and committed NEXT remain zero',()=>{const s=createState(),result=pure(appendLeader,s,record());assert.equal(result.state.logs[0].length,1);assert.equal(result.state.highWatermark,0);assert.equal(result.state.committedNext,0);assert.deepEqual(availableRecords(result.state),[]);assert.throws(()=>acknowledgeRecord(result.state,result.record),/ReplicationIncomplete/);});
test('all ISR replicas must fetch and confirm, even when minimum ISR is two',()=>{const a=appendLeader(createState(),record());let s=pure(replicateRecord,a.state,1,0);assert.equal(s.logs[1].length,1);s=pure(confirmReplication,s);assert.equal(s.highWatermark,0);assert.throws(()=>acknowledgeRecord(s,a.record),/ReplicationIncomplete/);s=pure(replicateRecord,s,2,0);s=pure(confirmReplication,s);assert.equal(s.highWatermark,1);assert.deepEqual(s.replicaHW,[1,0,0]);assert.equal(pure(acknowledgeRecord,s,a.record).response.acks,'all');s=pure(learnHighWatermark,s,1);s=pure(learnHighWatermark,s,2);assert.deepEqual(s.replicaHW,[1,1,1]);assert.equal(availableRecords(s).length,1);});
test('acks=0 has no broker response; acks=1 acknowledges the leader before replication',()=>{for(const acks of ['0','1']){const a=appendLeader(createState({acks,idempotent:false}),record());const ack=pure(acknowledgeRecord,a.state,a.record);assert.equal(ack.state.highWatermark,0);assert.deepEqual(ack.response,acks==='0'?null:{acks:'1',offset:0});assert.deepEqual(availableRecords(ack.state),[]);const elected=electLeader(failBroker(ack.state,0));assert.equal(elected.logs[elected.leader].length,0);assert.equal(elected.highWatermark,0);}});
test('all-acknowledged records survive a clean ISR election',()=>{const a=replicated();let s=pure(failBroker,a.state,0);assert.equal(s.leader,null);s=pure(electLeader,s,1);assert.equal(s.logs[1][0].eventId,a.record.eventId);assert.equal(s.highWatermark,1);assert.equal(s.metadata.producer,0);assert.equal(s.metadata.consumer,0);});
test('lost ACK retry deduplicates producer ID, epoch, partition and sequence after election',()=>{const a=replicated();let s=electLeader(failBroker(a.state,0),1);s=pure(refreshMetadata,s,'producer',2);const retry=pure(appendLeader,s,record(0,{eventId:'different-payload-does-not-create-a-second-sequence'}));assert.equal(retry.duplicate,true);assert.equal(retry.state.logs[1].length,1);assert.equal(retry.record.eventId,a.record.eventId);assert.equal(acknowledgeRecord(retry.state,retry.record).response.offset,0);const fresh=appendLeader(retry.state,record(1));assert.equal(fresh.duplicate,false);assert.equal(fresh.state.logs[1].length,2);});
test('business event ID alone cannot deduplicate producer writes',()=>{let s=appendLeader(createState(),record()).state;s=appendLeader(s,record(1)).state;s=appendLeader(s,record(0,{producerId:43})).state;assert.equal(s.logs[0].length,3);const nonIdempotent=createState({acks:'1',idempotent:false});const a=appendLeader(nonIdempotent,record());assert.equal(appendLeader(a.state,record()).state.logs[0].length,2);});
test('producer epoch fencing, sequence gaps and incompatible idempotence configuration reject',()=>{const s=appendLeader(createState(),record(0,{epoch:1})).state;assert.throws(()=>appendLeader(s,record()),/InvalidProducerEpoch/);assert.throws(()=>appendLeader(s,record(2,{epoch:1})),/OutOfOrderSequenceNumber/);assert.throws(()=>createState({acks:'0',idempotent:true}),/ConfigException/);assert.throws(()=>createState({acks:'1',idempotent:true}),/ConfigException/);});
test('ISR below minimum rejects a new all write without blocking already committed reads',()=>{let s=replicated().state;s=failBroker(failBroker(s,1),2);assert.deepEqual(s.isr,[0]);assert.throws(()=>appendLeader(s,record(1)),/^Error: NotEnoughReplicas$/);assert.equal(s.logs[0].length,1);assert.equal(availableRecords(s).length,1);});
test('clean election cannot choose a non-ISR or unavailable replica',()=>{let s=replicated().state;s={...s,isr:[0,1]};s=failBroker(s,0);assert.throws(()=>electLeader(s,2),/NoEligibleInSyncReplica/);s=failBroker(s,1);assert.throws(()=>electLeader(s),/NoEligibleInSyncReplica/);});
test('producer, consumer and coordinator rediscovery are independent pure transitions',()=>{let s=replicated().state;s=electLeader(failBroker(s,0),1);s=pure(refreshMetadata,s,'producer',2);assert.deepEqual(s.metadata,{producer:1,consumer:0,coordinator:0});s=pure(refreshMetadata,s,'consumer',2);assert.equal(s.metadata.coordinator,0);s=pure(rediscoverCoordinator,s,2);assert.deepEqual(s.metadata,{producer:1,consumer:1,coordinator:2});assert.equal(s.coordinator,2);});
test('processing, stored commit and acknowledged NEXT are separate pure steps',()=>{const a=replicated();let s=pure(receiveRecord,a.state,a.record);assert.equal(s.position,1);assert.throws(()=>storeCommit(s,1),/UnprocessedCommit/);s=pure(completeProcessing,s,a.record);assert.equal(s.committedNext,0);s=pure(storeCommit,s,1);assert.equal(s.committedNext,1);assert.equal(s.acknowledgedNext,0);s=pure(acknowledgeCommit,s);assert.equal(s.acknowledgedNext,1);assert.equal(s.logs[0].length,1);assert.deepEqual(s.journal.slice(-4).map(e=>e.phase),['received','processed','commit-stored','commit-ack']);});
