export const SCENES = Object.freeze([
  { id: "publish-once", navLabel: "One event", act: "The case begins", prompt: "The buyer submitted one dispute but three teams need to react. Does customer-info wait for all three?", title: "One dispute. Three independent reactions.", reveal: "customer-info publishes DisputeCreated once; Orders, Finance, and Message Center work independently.", takeaway: "One event can create independent outcomes.", evidence: [["Topic", "customer-info.disputes"], ["Event", "DisputeCreated → three consumers"]] },
  { id: "event-contract", navLabel: "Contract", act: "The case begins", prompt: "What must Finance receive before it trusts the event enough to block a payout?", title: "An event is a contract.", reveal: "Finance receives event_id, dispute_id, order_id, reason, occurred_at, and schema_version. response_due_at is an optional compatible addition.", takeaway: "Consumers need stable facts and compatible change.", evidence: [["event_id", "evt-001"], ["schema", "v1; response_due_at optional"]] },
  { id: "ordering", navLabel: "Ordering", act: "The case begins", prompt: "The dispute is opened now and resolved later. How do we keep those moments in order?", title: "Route one order's story together.", reveal: "order-49328 routes related records to P1. A record without a key has no order-level routing guarantee.", takeaway: "Ordering is per partition, so the key is a business decision.", evidence: [["Key", "order-49328 → P1"], ["No key", "available/sticky partition"], ["Order", "guaranteed within P1"]] },
  { id: "durability", navLabel: "Durability", act: "Make publishing safe", prompt: "The first broker failed immediately after receiving the dispute. Was the acknowledgement safe?", title: "Acknowledge only after the right copies exist.", reveal: "B1 leads, B2 and B3 follow. acks=all succeeds with ISR 3/3 and 2/3, then rejects the write at ISR 1/3 when min.insync.replicas is 2.", takeaway: "Acknowledgement is a durability decision.", evidence: [["Replicas", "B1 leader · B2/B3 followers"], ["ISR", "3/3 → 2/3 → 1/3"], ["Ack", "accepted → accepted → rejected"]] },
  { id: "consumer-progress", navLabel: "Progress", act: "Process reliably", prompt: "Orders adds another worker while Finance restarts. Will Orders duplicate banners, and how does Finance resume?", title: "Each service owns a group and a bookmark.", reveal: "Orders workers share its group; Finance has its own group and resumes after its committed offset.", takeaway: "Groups scale a service; committed offsets record group progress.", evidence: [["Orders", "orders-1 + orders-2 share work"], ["Finance", "committed offset 42"], ["Message Center", "committed independently"]] },
  { id: "retry", navLabel: "Retry", act: "Process reliably", prompt: "Finance cannot reach its payout store. Should it mark the event complete?", title: "Do not move the bookmark yet.", reveal: "Finance attempt 1 fails, so committed offset remains 41 and offset 42 is retried. Other services remain complete.", takeaway: "Commit after the business effect succeeds.", evidence: [["Finance", "attempt 1 failed"], ["Offset", "41 committed; 42 retry pending"], ["Other services", "complete"]] },
  { id: "idempotency", navLabel: "Duplicate", act: "Process reliably", prompt: "Finance blocked the payout but crashed before committing. Can it do that work twice?", title: "A redelivery must be harmless.", reveal: "Offset 42 returns as attempt 2. Finance sees evt-001 already applied and ignores the duplicate business effect.", takeaway: "Kafka can redeliver; the business service must be idempotent.", evidence: [["Attempt 2", "duplicate ignored"], ["event_id", "evt-001"], ["Business effect", "one payout block"]] },
  { id: "history", navLabel: "History", act: "Recover and look back", prompt: "Analytics joins today and Message Center missed yesterday. Who should read history?", title: "A retained log gives each group a choice.", reveal: "Fresh Analytics can start at latest or earliest; Message Center resets its existing offset to replay retained records. DisputeResolved is appended at offset 43.", takeaway: "Retention supports recovery and new readers; corrections append events.", evidence: [["Analytics latest", "future records only"], ["Analytics earliest", "retained records"], ["Message Center", "reset and replay"], ["New fact", "DisputeResolved @ 43"]] }
]);
export const initialLessonState = () => ({ sceneIndex: 0, phase: "prompt" });
export const advanceLesson = ({ sceneIndex, phase }) => phase === "prompt" ? { sceneIndex, phase: "reveal" } : { sceneIndex: Math.min(sceneIndex + 1, SCENES.length - 1), phase: "prompt" };
export const retreatLesson = ({ sceneIndex, phase }) => phase === "reveal" ? { sceneIndex, phase: "prompt" } : sceneIndex ? { sceneIndex: sceneIndex - 1, phase: "reveal" } : initialLessonState();
export const replayScene = ({ sceneIndex }) => ({ sceneIndex, phase: "prompt" });
export const restartStory = initialLessonState;
export const lessonCommandForKey = (key, shiftKey = false) => key === " " || key === "ArrowRight" ? "advance" : key === "ArrowLeft" ? "back" : key.toLowerCase() === "r" && shiftKey ? "restart-story" : key.toLowerCase() === "r" ? "replay" : null;
export const animationStageForPhase = (phase) => phase === "reveal" ? "consumer" : "producer";
export const SIMPLE_DELIVERY_STEPS = Object.freeze([
  { id: "created", label: "customer-info creates one DisputeCreated event" },
  { id: "appended", label: "Kafka appends that one event to P1 at offset 42" },
  { id: "read", label: "Three independent consumer groups read the same stored record" },
  { id: "effects", label: "Each service completes its own business effect" },
  { id: "commits", label: "Each group saves its own progress: offset 41 → 42" },
  { id: "outcome", label: "One stored event created three independent outcomes", committedOffsets: { orders: "42", finance: "42", message: "42" } }
]);
